# This workflow with build and push a Docker image dockerhub on every push to the master branch

name: Pushing Latest Release Image to Docker

on: 
  push:
    branches: 
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Login to DockerHub
      uses: docker/login-action@v1 
      with:
        username: ${{secrets.DOCKER_USER}}
        password: ${{secrets.DOCKER_PASS}}
    - name: Build and Push to Docker
      uses: docker/build-push-action@v2
      with:
        context: .
        push: true
        tags: bittensor/bittensor:latest
